Migration middleware-dev pour le faire pointer sur Archipelago
assemblee-virtuelle/deployment_semapps_av pull request #15
Opened 2022-01-27 13:24 UTC by fluidlog

https://github.com/assemblee-virtuelle/archipelago/issues/32

2022-01-27 16:28 UTC, srosset81 requested changes

2022-01-27 16:28 UTC, srosset81 commented on docker-compose-dev.yaml
> +    container_name: middleware-dev
Il faudrait aussi utiliser middleware-dev pour la clé (ligne 18)

2022-01-27 16:28 UTC, srosset81 commented on docker-compose-dev.yaml
> -        - SELECTED_BRANCH=master
Il faut garder cette ligne. Elle est utile pour indiquer qu'on veut déployer une autre branche.

2022-01-27 16:28 UTC, srosset81 commented on docker-compose.yaml
> -        - SELECTED_BRANCH=master
Ne pas supprimer

2022-02-16 12:39 UTC, fluidlog commented on docker-compose.yaml
> -        - SELECTED_BRANCH=master
Je les avais retiré car dans le Dockerfile, on écrit : 
ARG SELECTED_BRANCH=master
Mais bon, je vais la remettre, il y a peut-être quelque chose que je n'ai pas compris.

2022-02-16 12:40 UTC, fluidlog commented on docker-compose-dev.yaml
> +    container_name: middleware-dev
Merci :)

2022-02-16 13:53 UTC, srosset81 approved these changes

2022-02-16 13:54 UTC, srosset81 commented on docker-compose.yaml
> -        - SELECTED_BRANCH=master
Oui ça ne change rien, mais ça aide à comprendre là où on peut mettre la config

2022-02-16 14:18 UTC, merged